[build]
  command = "mkdir -p dist && cp -a dphilhower-studio-wp/preview/. dist/"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[context.deploy-preview]
  command = "mkdir -p dist && cp -a dphilhower-studio-wp/preview/. dist/"
