<?php

declare(strict_types=1);

return [
    'name' => 'Bville Pizza & Grill',
    'short_name' => 'Bville',
    'tagline' => 'For the table.',
    'address' => '159 Morristown Rd',
    'city' => 'Bernardsville, NJ 07924',
    'phone' => '(908) 766-1666',
    'phone_raw' => '9087661666',
    'email' => 'info@bvillepizzagrill.com',
    'hours' => 'Open daily — call for hours',
    'geo' => [
        'street' => '159 Morristown Rd',
        'locality' => 'Bernardsville',
        'region' => 'NJ',
        'postal' => '07924',
        'country' => 'US',
    ],
    'order' => [
        'path' => 'order/',
        'cta' => 'Order Online',
        'pickup' => 'Pickup',
        'delivery' => 'Delivery',
    ],
    'house_checks' => [
        [
            'no' => '01',
            'tag' => 'House pie',
            'name' => "B'Ville Special",
            'desc' => 'Shawarma chicken, garlic drizzle',
            'price' => '12" 14.95 · 16" 20.95',
            'item' => 'pizza-bville-special',
        ],
        [
            'no' => '02',
            'tag' => 'Jersey grill',
            'name' => 'Jersey Cheesesteak',
            'desc' => 'Brown gravy potatoes & mozzarella',
            'price' => '10.95',
            'item' => 'cheesesteak-jersey',
        ],
        [
            'no' => '03',
            'tag' => 'Angus',
            'name' => 'Chetzel',
            'desc' => 'Bacon, cheddar & jack on pretzel bun',
            'price' => '12.95',
            'item' => 'burgers-chetzel',
        ],
    ],
    'social' => [
        'instagram' => 'https://www.instagram.com/bvillepizzagrill/',
        'facebook' => '',
    ],
    'about' => 'The Grill is now Bville Pizza and Grill! Although our name has changed, the high-quality Mediterranean and American cuisine we serve our customers in the Bernardsville area remains the same. From chicken wings to paninis to kabobs, our food will be sure to please. Check out our creative selection of pizzas, the latest addition to our menu. Whether you are a returning customer or thinking about trying us for the first time, you\'ll find something on our diverse menu to satisfy your appetite. But don\'t take our word for it, check out our 4-star ratings on Google, Yelp, and Trip Advisor!',
    'heritage' => [
        'Stone oven pizza since the rebrand',
        'Mediterranean & American on one grill',
        'Cafe Robust coffee daily',
        '4-star local favorites on Google & Yelp',
    ],
    'photos' => [
        'hero' => 'assets/photos/pizza.jpg',
        'cafe' => 'assets/photos/coffee.jpg',
        'kitchen' => 'assets/photos/steam-kitchen.jpg',
        'pass' => 'assets/photos/exterior.jpg',
        'dining' => 'assets/photos/cafe-dining.jpg',
        'table' => 'assets/photos/table-spread.jpg',
        'plated' => 'assets/photos/plated-grill.jpg',
        'chef' => 'assets/photos/kitchen-bar.jpg',
        'angus' => 'assets/photos/burger.jpg',
        'bacon_burger' => 'assets/photos/panini.jpg',
        'restaurant' => 'assets/photos/house-dining-room.jpg',
        'sweet' => 'assets/photos/gelato-mascarpone.png',
        'dining-room' => 'assets/photos/house-dining-room.jpg',
        'oven-line' => 'assets/photos/house-stone-oven.jpg',
        'grill-fire' => 'assets/photos/house-grill-fire.jpg',
        'catering-trays' => 'assets/photos/house-catering-trays.jpg',
        'cobb-counter' => 'assets/photos/house-cobb-counter.jpg',
        'board-bbq-pie' => 'assets/photos/menu/pizza-bbq-buffalo.jpg',
        'board-classic-pie' => 'assets/photos/menu/pizza-classic.jpg',
        'board-shawarma' => 'assets/photos/menu/platters-shawarma.jpg',
        'board-chicken-parm' => 'assets/photos/menu/sandwiches-chicken-parm.jpg',
        'board-falafel' => 'assets/photos/menu/starters-falafel.jpg',
        'board-quesadilla' => 'assets/photos/menu/platters-quesadilla.jpg',
        'board-buffalo-wrap' => 'assets/photos/menu/wraps-buffalo-chicken.jpg',
        'board-milano' => 'assets/photos/menu/panini-milano.jpg',
        'board-cobb' => 'assets/photos/menu/garden-cobb.jpg',
        'board-tuna-melt' => 'assets/photos/menu/sandwiches-tuna-melt.jpg',
        'categories' => [
            'pizza' => 'assets/photos/pizza.jpg',
            'platters' => 'assets/photos/handhelds.jpg',
            'garden' => 'assets/photos/salad.jpg',
            'starters' => 'assets/photos/plated-grill.jpg',
            'wraps' => 'assets/photos/wraps.jpg',
            'pasta' => 'assets/photos/table-spread.jpg',
            'sandwiches' => 'assets/photos/sandwich.jpg',
            'panini' => 'assets/photos/sandwich.jpg',
            'burgers' => 'assets/photos/panini.jpg',
            'shakes' => 'assets/photos/cafe-dining.jpg',
            'kids' => 'assets/photos/sandwich.jpg',
            'cheesesteak' => 'assets/photos/sandwich.jpg',
            'desserts' => 'assets/photos/gelato-yogurt-berries.png',
        ],
        'alts' => [
            'hero' => 'Stone oven cheese pizza with cherry tomatoes and rosemary',
            'pizza' => 'Sliced stone oven cheese pizza on a wood board',
            'platters' => 'Char-grilled kebab platter with fries, pita, and tzatziki',
            'garden' => 'Fresh garden salad with greens, tomatoes, avocado, and vegetables',
            'starters' => 'Plated grill special with roasted potatoes and pastry',
            'wraps' => 'Chicken vegetable wraps cut to show the filling',
            'pasta' => 'Table spread of grilled plates, bread, and house sides',
            'sandwiches' => 'Toasted sandwich with melted cheese and house sauces',
            'panini' => 'Pressed sandwich with grill marks, cheese, and dipping sauces',
            'burgers' => 'Stacked bacon cheeseburger with lettuce, tomato, and special sauce',
            'shakes' => 'Cafe table with milkshakes and a guest reading the menu',
            'kids' => 'Toasted grilled sandwich, a kids-menu favorite',
            'cheesesteak' => 'Pressed cheesesteak sandwich',
            'desserts' => 'Yogurt and berry gelato coppa',
            'cafe' => 'Latte art and iced coffee toast at Cafe Robust',
            'kitchen' => 'Stock pots steaming with fresh vegetables in the kitchen',
            'pass' => 'Chefs working the kitchen pass under heat lamps',
            'dining' => 'Warm dining room with milkshakes and a guest at the table',
            'table' => 'Plated grill dinners on a rustic wood table',
            'plated' => 'Sliced roast with gravy, pastry, and vegetables',
            'chef' => 'Chef plating a grill special with a dark reduction',
            'angus' => 'Angus burgers on a wood board with avocado and greens',
            'bacon_burger' => 'Bacon cheeseburger stacked on a sesame bun',
            'restaurant' => 'The Bville dining room at 159 Morristown Rd',
            'sweet' => 'Mascarpone gelato with a caramelized top',
            'dining-room' => 'The Bville dining room at 159 Morristown Rd',
            'oven-line' => 'The stone oven behind the counter',
            'grill-fire' => 'Bacon over open flame on the char grill',
            'catering-trays' => 'Catering trays of cutlets, peppers, and wings on the pass',
            'cobb-counter' => 'Cobb salad at the counter',
            'board-bbq-pie' => 'Half BBQ, half buffalo chicken pie in the case',
            'board-classic-pie' => 'Whole classic cheese pie on the stand',
            'board-shawarma' => 'Chicken shawarma platter with yellow rice and salad',
            'board-chicken-parm' => 'Chicken parm sandwich cut to the pull',
            'board-falafel' => 'Falafel with lettuce and tahini',
            'board-quesadilla' => 'Chicken quesadilla with sour cream and pico',
            'board-buffalo-wrap' => 'Buffalo chicken wrap with seasoned fries',
            'board-milano' => 'Milano panini with pesto and mozzarella',
            'board-cobb' => 'Cobb salad with bacon, avocado, and egg',
            'board-tuna-melt' => 'Tuna sandwich with a basket of fries',
        ],
        'gallery' => [
            ['key' => 'board-bbq-pie', 'caption' => 'BBQ & buffalo pie'],
            ['key' => 'board-classic-pie', 'caption' => 'The classic pie'],
            ['key' => 'board-shawarma', 'caption' => 'Shawarma platter'],
            ['key' => 'board-chicken-parm', 'caption' => 'Chicken parm'],
            ['key' => 'board-falafel', 'caption' => 'Falafel'],
            ['key' => 'board-quesadilla', 'caption' => 'Quesadilla'],
            ['key' => 'board-buffalo-wrap', 'caption' => 'Buffalo wrap'],
            ['key' => 'board-milano', 'caption' => 'The Milano'],
            ['key' => 'board-cobb', 'caption' => 'Cobb'],
            ['key' => 'board-tuna-melt', 'caption' => 'Tuna on rye'],
            ['key' => 'cobb-counter', 'caption' => 'At the counter'],
            ['key' => 'grill-fire', 'caption' => 'The grill'],
            ['key' => 'oven-line', 'caption' => 'The stone oven'],
            ['key' => 'dining-room', 'caption' => 'The dining room'],
            ['key' => 'catering-trays', 'caption' => 'Catering on the pass'],
        ],
    ],
    'menu_categories' => [
        ['id' => 'pizza', 'label' => 'Stone Oven Baked'],
        ['id' => 'platters', 'label' => 'Headlines'],
        ['id' => 'garden', 'label' => 'From The Garden'],
        ['id' => 'starters', 'label' => 'Starters'],
        ['id' => 'wraps', 'label' => 'Wrap & Roll'],
        ['id' => 'pasta', 'label' => 'Pastabilities'],
        ['id' => 'cheesesteak', 'label' => 'Cheesesteak'],
        ['id' => 'sandwiches', 'label' => 'Sandwiches'],
        ['id' => 'panini', 'label' => 'Panini'],
        ['id' => 'burgers', 'label' => 'Burgers'],
        ['id' => 'kids', 'label' => 'Kids Menu'],
        ['id' => 'desserts', 'label' => 'Sweet Endings'],
    ],
    'cafe_robust' => [
        'name' => 'Cafe Robust',
        'tagline' => 'Bold coffee · Fresh roasts',
        'colors' => [
            'brown' => '#4B2C20',
            'gold' => '#D4A34F',
            'white' => '#FFFFFF',
        ],
        'logos' => [
            'bean' => 'assets/cafe-robust/bean-logo.svg',
            'cup' => 'assets/cafe-robust/cup-logo.svg',
            'wordmark' => 'assets/cafe-robust/wordmark-bubble.svg',
            'arch' => 'assets/cafe-robust/wordmark-arch.svg',
            'cr' => 'assets/cafe-robust/cr-mark.svg',
        ],
        'drinks' => [
            ['name' => 'Robust House Blend', 'slug' => 'robust-house-blend', 'desc' => 'Dark roast, smooth finish', 'price' => '2.99'],
            ['name' => 'Espresso', 'desc' => 'Single or double shot', 'price' => '2.49'],
            ['name' => 'Cappuccino', 'desc' => 'Steamed milk, thick foam', 'price' => '4.49'],
            ['name' => 'Latte', 'desc' => 'Espresso with steamed milk', 'price' => '4.99'],
            ['name' => 'Cold Brew', 'desc' => 'Slow-steeped, served over ice', 'price' => '4.49'],
            ['name' => 'Seasonal Special', 'desc' => 'Ask your barista', 'price' => '5.49'],
        ],
    ],
    'designer' => [
        'name' => 'Philhower',
        'studio' => 'Warped Minds Design',
        'person' => 'David Philhower',
        'logo' => 'assets/philhower/philhower-logo.svg',
        'url' => 'https://linkedin.com/in/david-philhower-984264169',
        'colors' => [
            'purple' => '#5B2488',
            'blue' => '#1E4FA8',
            'gold' => '#F5C518',
            'navy' => '#0D2B6E',
        ],
    ],
    'menu_graphic' => [
        'ai' => 'assets/source/graphic for front menu deli bernardsville.ai',
        'idlk' => 'assets/source/~bernardsville deli~07z_p2.idlk',
        'export_png' => 'public/assets/menu/front-menu.png',
        'export_jpg' => 'public/assets/menu/front-menu.jpg',
        'export_webp' => 'public/assets/menu/front-menu.webp',
        'placeholder' => 'assets/menu/front-menu-board.svg',
    ],
];
