<?php

declare(strict_types=1);

return [
    'name' => 'Bville Pizza & Grill',
    'short_name' => 'Bville',
    'tagline' => 'Check out Bville Pizza & Grill!',
    'address' => '159 Morristown Rd',
    'city' => 'Bernardsville, NJ 07924',
    'phone' => '(908) 766-1666',
    'phone_raw' => '9087661666',
    'email' => 'info@bvillepizzagrill.com',
    'hours' => 'Open daily — call for hours',
    'social' => [
        'instagram' => '#',
        'facebook' => '#',
    ],
    'about' => 'The Grill is now Bville Pizza and Grill! Although our name has changed, the high-quality Mediterranean and American cuisine we serve our customers in the Bernardsville area remains the same. From chicken wings to paninis to kabobs, our food will be sure to please. Check out our creative selection of pizzas, the latest addition to our menu. Whether you are a returning customer or thinking about trying us for the first time, you\'ll find something on our diverse menu to satisfy your appetite. But don\'t take our word for it, check out our 4-star ratings on Google, Yelp, and Trip Advisor!',
    'heritage' => [
        'Stone oven pizza since the rebrand',
        'Mediterranean & American on one grill',
        'Cafe Robust coffee daily',
        '4-star local favorites on Google & Yelp',
    ],
    'yelp' => 'https://yelp.to/viEc5U-sWj',
    'photo_credit' => 'Guest photos from the Bville Pizza & Grill Yelp listing',
    'photos' => [
        'hero' => 'assets/photos/pizza.jpg',
        'cafe' => 'assets/photos/coffee.jpg',
        'kitchen' => 'assets/photos/listing/chicken-kabob-salad.jpg',
        'pass' => 'assets/photos/listing/menu-cover.jpg',
        'dining' => 'assets/photos/listing/interior.jpg',
        'table' => 'assets/photos/listing/falafel-salad.jpg',
        'plated' => 'assets/photos/listing/chicken-platter.jpg',
        'chef' => 'assets/photos/listing/interior-alt.jpg',
        'angus' => 'assets/photos/listing/chicken-pesto-sub.jpg',
        'bacon_burger' => 'assets/photos/listing/quesadilla.jpg',
        'restaurant' => 'assets/photos/listing/interior.jpg',
        'categories' => [
            'pizza' => 'assets/photos/pizza.jpg',
            'platters' => 'assets/photos/listing/chicken-platter.jpg',
            'garden' => 'assets/photos/listing/chicken-kabob-salad.jpg',
            'starters' => 'assets/photos/listing/falafel.jpg',
            'wraps' => 'assets/photos/listing/wrap-fries.jpg',
            'pasta' => 'assets/photos/listing/falafel-salad.jpg',
            'sandwiches' => 'assets/photos/listing/sandwich-fries.jpg',
            'panini' => 'assets/photos/listing/chicken-pesto-sub.jpg',
            'burgers' => 'assets/photos/listing/chicken-pesto-sub.jpg',
            'shakes' => 'assets/photos/listing/interior.jpg',
            'kids' => 'assets/photos/listing/sandwich-fries.jpg',
            'cheesesteak' => 'assets/photos/listing/quesadilla.jpg',
            'desserts' => 'assets/photos/gelato-yogurt-berries.png',
        ],
        'alts' => [
            'hero' => 'Loaded pizza with olives, peppers, and cheese pull from the Bville menu',
            'pizza' => 'Supreme pizza with olives, peppers, onions, and sausage',
            'platters' => 'Chicken shawarma platter with yellow rice, peppers, and salad',
            'garden' => 'Chicken kabob salad with eggs, bacon, cheese, and ranch',
            'starters' => 'Falafel with tahini and shredded lettuce',
            'wraps' => 'Chicken wrap in newspaper wrap with a side of fries',
            'pasta' => 'Falafel Greek salad with feta, olives, cucumber, and tomato',
            'sandwiches' => 'Toasted sandwich with fries in a wire basket',
            'panini' => 'Chicken pesto sub with a mozzarella cheese pull',
            'burgers' => 'Chicken pesto hero with melted mozzarella',
            'shakes' => 'Bville dining room with globe lights and wood tables',
            'kids' => 'Toasted sandwich and fries',
            'cheesesteak' => 'Chicken quesadilla with sour cream and pico de gallo',
            'desserts' => 'Yogurt and berry gelato coppa',
            'cafe' => 'Latte art and iced coffee toast at Cafe Robust',
            'kitchen' => 'Chicken kabob salad from the Bville grill',
            'pass' => 'Bville Pizza & Grill takeout menu cover',
            'dining' => 'Warm dining room with wood tables and mosaic pendant lights',
            'table' => 'Falafel salad with feta and Kalamata olives',
            'plated' => 'Chicken platter with rice, peppers, and house salad',
            'chef' => 'Dining room looking toward the front windows',
            'angus' => 'Chicken pesto sub with melted cheese',
            'bacon_burger' => 'Chicken quesadilla wedges with pico and sour cream',
            'restaurant' => 'Dining room tables set for service',
        ],
        'gallery' => [
            ['key' => 'pizza', 'caption' => 'Stone oven pizza'],
            ['key' => 'platters', 'caption' => 'Grill platters'],
            ['key' => 'starters', 'caption' => 'Falafel'],
            ['key' => 'wraps', 'caption' => 'Wraps'],
            ['key' => 'panini', 'caption' => 'Pressed sandwiches'],
            ['key' => 'garden', 'caption' => 'From the garden'],
            ['key' => 'table', 'caption' => 'Salads'],
            ['key' => 'dining', 'caption' => 'The dining room'],
        ],
    ],
    'menu_categories' => [
        ['id' => 'pizza', 'label' => 'Stone Oven Baked'],
        ['id' => 'platters', 'label' => 'Headlines'],
        ['id' => 'garden', 'label' => 'From The Garden'],
        ['id' => 'starters', 'label' => 'Starters'],
        ['id' => 'wraps', 'label' => 'Wrap & Roll'],
        ['id' => 'pasta', 'label' => 'Pastabilities'],
        ['id' => 'cheesesteak', 'label' => 'Cheesesteak'],
        ['id' => 'sandwiches', 'label' => 'Sandwiches'],
        ['id' => 'panini', 'label' => 'Panini'],
        ['id' => 'burgers', 'label' => 'Burgers'],
        ['id' => 'kids', 'label' => 'Kids Menu'],
        ['id' => 'desserts', 'label' => 'Sweet Endings'],
    ],
    'cafe_robust' => [
        'name' => 'Cafe Robust',
        'tagline' => 'Bold coffee · Fresh roasts',
        'colors' => [
            'brown' => '#4B2C20',
            'gold' => '#D4A34F',
            'white' => '#FFFFFF',
        ],
        'logos' => [
            'bean' => 'assets/cafe-robust/bean-logo.svg',
            'cup' => 'assets/cafe-robust/cup-logo.svg',
            'wordmark' => 'assets/cafe-robust/wordmark-bubble.svg',
            'arch' => 'assets/cafe-robust/wordmark-arch.svg',
            'cr' => 'assets/cafe-robust/cr-mark.svg',
        ],
        'drinks' => [
            ['name' => 'Robust House Blend', 'slug' => 'robust-house-blend', 'desc' => 'Dark roast, smooth finish', 'price' => '2.99'],
            ['name' => 'Espresso', 'desc' => 'Single or double shot', 'price' => '2.49'],
            ['name' => 'Cappuccino', 'desc' => 'Steamed milk, thick foam', 'price' => '4.49'],
            ['name' => 'Latte', 'desc' => 'Espresso with steamed milk', 'price' => '4.99'],
            ['name' => 'Cold Brew', 'desc' => 'Slow-steeped, served over ice', 'price' => '4.49'],
            ['name' => 'Seasonal Special', 'desc' => 'Ask your barista', 'price' => '5.49'],
        ],
    ],
    'designer' => [
        'name' => 'Philhower',
        'studio' => 'Warped Minds Design',
        'person' => 'David Philhower',
        'logo' => 'assets/philhower/philhower-logo.svg',
        'url' => 'https://linkedin.com/in/david-philhower-984264169',
        'colors' => [
            'purple' => '#5B2488',
            'blue' => '#1E4FA8',
            'gold' => '#F5C518',
            'navy' => '#0D2B6E',
        ],
    ],
    'menu_graphic' => [
        'ai' => 'assets/source/graphic for front menu deli bernardsville.ai',
        'idlk' => 'assets/source/~bernardsville deli~07z_p2.idlk',
        'export_png' => 'public/assets/menu/front-menu.png',
        'export_jpg' => 'public/assets/menu/front-menu.jpg',
        'export_webp' => 'public/assets/menu/front-menu.webp',
        'placeholder' => 'assets/menu/front-menu-board.svg',
    ],
];
