<?php

declare(strict_types=1);

return [
    'name' => 'Bville Pizza & Grill',
    'short_name' => 'Bville',
    'tagline' => 'Stone oven pizza · Mediterranean & American cuisine',
    'address' => '159 Morristown Rd',
    'city' => 'Bernardsville, NJ 07924',
    'phone' => '(908) 766-1666',
    'phone_raw' => '9087661666',
    'email' => 'info@bvillepizzagrill.com',
    'hours' => 'Open daily — call for hours',
    'social' => [
        'instagram' => '#',
        'facebook' => '#',
    ],
    'about' => 'The Grill is now Bville Pizza and Grill! Although our name has changed, the high-quality Mediterranean and American cuisine we serve our customers in the Bernardsville area remains the same. From chicken wings to paninis to kabobs, our food will be sure to please. Check out our creative selection of pizzas, the latest addition to our menu. Whether you are a returning customer or thinking about trying us for the first time, you\'ll find something on our diverse menu to satisfy your appetite. But don\'t take our word for it, check out our 4-star ratings on Google, Yelp, and Trip Advisor!',
    'heritage' => [
        'Stone oven pizza since the rebrand',
        'Mediterranean & American on one grill',
        'Cafe Robust coffee daily',
        '4-star local favorites on Google & Yelp',
    ],
    'photos' => [
        'hero' => 'assets/photos/pizza.jpg',
        'cafe' => 'assets/photos/coffee.jpg',
        'kitchen' => 'assets/photos/steam-kitchen.jpg',
        'pass' => 'assets/photos/exterior.jpg',
        'dining' => 'assets/photos/cafe-dining.jpg',
        'table' => 'assets/photos/table-spread.jpg',
        'plated' => 'assets/photos/plated-grill.jpg',
        'chef' => 'assets/photos/kitchen-bar.jpg',
        'angus' => 'assets/photos/burger.jpg',
        'bacon_burger' => 'assets/photos/panini.jpg',
        'restaurant' => 'assets/photos/hero-restaurant.jpg',
        'categories' => [
            'pizza' => 'assets/photos/pizza.jpg',
            'platters' => 'assets/photos/handhelds.jpg',
            'garden' => 'assets/photos/wraps.jpg',
            'starters' => 'assets/photos/plated-grill.jpg',
            'wraps' => 'assets/photos/wraps.jpg',
            'pasta' => 'assets/photos/table-spread.jpg',
            'sandwiches' => 'assets/photos/sandwich.jpg',
            'panini' => 'assets/photos/sandwich.jpg',
            'burgers' => 'assets/photos/panini.jpg',
            'shakes' => 'assets/photos/cafe-dining.jpg',
            'kids' => 'assets/photos/sandwich.jpg',
        ],
        'alts' => [
            'hero' => 'Stone oven cheese pizza with cherry tomatoes and rosemary',
            'pizza' => 'Sliced stone oven cheese pizza on a wood board',
            'platters' => 'Char-grilled kebab platter with fries, pita, and tzatziki',
            'garden' => 'Fresh chicken and vegetable wraps on a wood tray',
            'starters' => 'Plated grill special with roasted potatoes and pastry',
            'wraps' => 'Chicken vegetable wraps cut to show the filling',
            'pasta' => 'Table spread of grilled plates, bread, and house sides',
            'sandwiches' => 'Toasted sandwich with melted cheese and house sauces',
            'panini' => 'Pressed sandwich with grill marks, cheese, and dipping sauces',
            'burgers' => 'Stacked bacon cheeseburger with lettuce, tomato, and special sauce',
            'shakes' => 'Cafe table with milkshakes and a guest reading the menu',
            'kids' => 'Toasted grilled sandwich, a kids-menu favorite',
            'cafe' => 'Latte art and iced coffee toast at Cafe Robust',
            'kitchen' => 'Stock pots steaming with fresh vegetables in the kitchen',
            'pass' => 'Chefs working the kitchen pass under heat lamps',
            'dining' => 'Warm dining room with milkshakes and a guest at the table',
            'table' => 'Plated grill dinners on a rustic wood table',
            'plated' => 'Sliced roast with gravy, pastry, and vegetables',
            'chef' => 'Chef plating a grill special with a dark reduction',
            'angus' => 'Angus burgers on a wood board with avocado and greens',
            'bacon_burger' => 'Bacon cheeseburger stacked on a sesame bun',
            'restaurant' => 'Dining room tables set for service',
        ],
        'gallery' => [
            ['key' => 'pizza', 'caption' => 'Stone oven pizza'],
            ['key' => 'platters', 'caption' => 'Grill platters'],
            ['key' => 'burgers', 'caption' => 'Angus burgers'],
            ['key' => 'wraps', 'caption' => 'Wraps'],
            ['key' => 'panini', 'caption' => 'Pressed sandwiches'],
            ['key' => 'cafe', 'caption' => 'Cafe Robust'],
            ['key' => 'table', 'caption' => 'From the kitchen'],
            ['key' => 'kitchen', 'caption' => 'Made to order'],
        ],
    ],
    'menu_categories' => [
        ['id' => 'pizza', 'label' => 'Stone Oven Pizza'],
        ['id' => 'platters', 'label' => 'Platters'],
        ['id' => 'garden', 'label' => 'Garden'],
        ['id' => 'starters', 'label' => 'Starters'],
        ['id' => 'wraps', 'label' => 'Wraps'],
        ['id' => 'pasta', 'label' => 'Pastabilities'],
        ['id' => 'sandwiches', 'label' => 'Sandwiches'],
        ['id' => 'panini', 'label' => 'Panini'],
        ['id' => 'burgers', 'label' => 'Burgers'],
        ['id' => 'kids', 'label' => 'Kids Menu'],
    ],
    'cafe_robust' => [
        'name' => 'Cafe Robust',
        'tagline' => 'Bold coffee · Fresh roasts',
        'colors' => [
            'brown' => '#4B2C20',
            'gold' => '#D4A34F',
            'white' => '#FFFFFF',
        ],
        'logos' => [
            'bean' => 'assets/cafe-robust/bean-logo.svg',
            'cup' => 'assets/cafe-robust/cup-logo.svg',
            'wordmark' => 'assets/cafe-robust/wordmark-bubble.svg',
            'arch' => 'assets/cafe-robust/wordmark-arch.svg',
            'cr' => 'assets/cafe-robust/cr-mark.svg',
        ],
        'drinks' => [
            ['name' => 'Robust House Blend', 'slug' => 'robust-house-blend', 'desc' => 'Dark roast, smooth finish', 'price' => '2.99'],
            ['name' => 'Espresso', 'desc' => 'Single or double shot', 'price' => '2.49'],
            ['name' => 'Cappuccino', 'desc' => 'Steamed milk, thick foam', 'price' => '4.49'],
            ['name' => 'Latte', 'desc' => 'Espresso with steamed milk', 'price' => '4.99'],
            ['name' => 'Cold Brew', 'desc' => 'Slow-steeped, served over ice', 'price' => '4.49'],
            ['name' => 'Seasonal Special', 'desc' => 'Ask your barista', 'price' => '5.49'],
        ],
    ],
    'designer' => [
        'name' => 'Philhower',
        'studio' => 'Warped Minds Design',
        'person' => 'David Philhower',
        'logo' => 'assets/philhower/philhower-logo.svg',
        'url' => 'https://linkedin.com/in/david-philhower-984264169',
        'colors' => [
            'purple' => '#5B2488',
            'blue' => '#1E4FA8',
            'gold' => '#F5C518',
            'navy' => '#0D2B6E',
        ],
    ],
    'menu_graphic' => [
        'ai' => 'assets/source/graphic for front menu deli bernardsville.ai',
        'idlk' => 'assets/source/~bernardsville deli~07z_p2.idlk',
        'export_png' => 'public/assets/menu/front-menu.png',
        'export_jpg' => 'public/assets/menu/front-menu.jpg',
        'export_webp' => 'public/assets/menu/front-menu.webp',
        'placeholder' => 'assets/menu/front-menu-board.svg',
    ],
];
