<?php

declare(strict_types=1);

return [
    [
        'id' => 'garden',
        'title' => 'From The Garden',
        'wordmark' => 'garden',
        'watermark' => 'Fresh Salad',
        'note' => 'Add on: Chicken 4 · Grilled Salmon 7 · Shawarma 6 · Tuna Salad 4 · Steak 8 · Gyro (Lamb) 5 · Chicken Kabab 7 · Buffalo Chicken 4 · Cajun Salmon 8 (spicy) · Cajun Chicken 5 (spicy) · Shrimp 6',
        'items' => [
            ['name' => 'House', 'desc' => 'Romaine lettuce, tomatoes, cucumbers, carrots & red onions with oil & vinegar', 'price' => '7.95'],
            ['name' => 'Greek', 'desc' => 'Romaine lettuce, tomatoes, cucumbers, olives, red onions & feta cheese with greek vinaigrette', 'price' => '9.95'],
            ['name' => 'Caesar', 'desc' => 'Romaine lettuce with our freshly made Caesar dressing, parmesan cheese & croûtons', 'price' => '7.95'],
            ['name' => 'Baby Spinach', 'desc' => 'Spinach, strawberries, walnuts & goat cheese with balsamic vinaigrette', 'price' => '9.95'],
            ['name' => 'Arugula', 'desc' => 'Roasted red peppers, red onions, Parmesan cheese, with balsamic glaze', 'price' => '9.95'],
            ['name' => 'Cobb', 'desc' => 'Mixed greens, tomatoes, cucumbers, boiled egg, crumbled blue cheese, bacon, & avocado with balsamic vinaigrette', 'price' => '9.95'],
            ['name' => 'Mixed Greens', 'desc' => 'Tomato, onion, cucumber, carrots & fresh mozzarella with raspberry vinaigrette', 'price' => '9.95'],
        ],
    ],
    [
        'id' => 'starters',
        'title' => 'Starters',
        'wordmark' => 'starters',
        'watermark' => "Let's Get It Started",
        'items' => [
            ['name' => 'Homemade Wings', 'desc' => 'Choice of bone-in or boneless (white meat) served with carrots, celery; buffalo, teriyaki, BBQ or sweet chili', 'price' => '8.95 / 14.95', 'note' => '(6) / (12)'],
            ['name' => 'Mozzarella Sticks', 'desc' => 'Golden-fried & served with marinara sauce', 'price' => '7.95'],
            ['name' => 'Fried Calamari', 'desc' => 'Choice of spicy or sweet marinara', 'price' => '10.95'],
            ['name' => 'Mac & Cheese Bites', 'desc' => 'Golden-fried & served with marinara sauce', 'price' => '7.95'],
            ['name' => 'Hummus', 'veg' => true, 'desc' => 'Homemade blended chick peas, lemon & tahini (pita or veggie)', 'price' => '7.95'],
            ['name' => 'Falafel', 'veg' => true, 'desc' => 'Ground mix of chick peas, onion, garlic & parsley with our secret spices', 'price' => '7.95'],
            ['name' => 'Teriyaki Dumplings', 'desc' => 'Fried chicken dumplings served with teriyaki sauce', 'price' => '7.95'],
            ['name' => 'Buffalo Chicken Mac & Cheese', 'price' => '9.95'],
            ['name' => 'Chicken Nuggets & Fries', 'desc' => '6 chicken nuggets with sauce', 'price' => '7.95'],
            ['name' => 'Chicken Tenders', 'desc' => '5 chicken tenders with fries & sauce', 'price' => '7.95'],
            ['name' => 'Rice', 'price' => '3.95'],
            ['name' => 'Sweet Potato Fries', 'price' => '3.95'],
            ['name' => 'French Fries', 'price' => '3.95'],
            ['name' => 'Disco Fries', 'price' => '6.95'],
            ['name' => 'Onion Rings', 'price' => '5.95'],
            ['name' => 'Sautéed Veggie', 'price' => '4.95'],
        ],
    ],
    [
        'id' => 'shakes',
        'title' => 'Shakes',
        'wordmark' => 'shakes',
        'items' => [
            ['name' => 'Milkshake', 'desc' => 'NutterButter, Cookies & Cream, Chocolate, Vanilla, Strawberry', 'price' => '4.95'],
        ],
    ],
    [
        'id' => 'burgers',
        'title' => 'Burgers',
        'wordmark' => 'burgers',
        'watermark' => 'Angus · Beefy',
        'note' => 'Angus · Beefy',
        'items' => [
            ['name' => 'Classic', 'desc' => 'With lettuce, tomato & onion', 'price' => '9.95'],
            ['name' => 'Cheese Deluxe', 'desc' => 'With lettuce, tomato, onion & American cheese', 'price' => '10.95'],
            ['name' => 'The Fry', 'desc' => 'Breaded chicken cutlet, coleslaw & pickles with fry sauce', 'price' => '10.95'],
            ['name' => 'Boom Boom', 'desc' => 'Naked (no bun) lettuce, tomato, avocado, bacon & boom-boom sauce', 'price' => '11.95'],
            ['name' => 'Chetzel', 'slug' => 'prime-rib-burger', 'desc' => 'Bacon, melted cheddar & jack cheese served on toasted pretzel bun', 'price' => '12.95'],
            ['name' => 'Shroom', 'desc' => 'Sautéed mushrooms & onions with swiss', 'price' => '10.95'],
            ['name' => 'Falafel Burger', 'veg' => true, 'desc' => 'Lettuce, tomato, & pickle with tahini sauce', 'price' => '9.95'],
        ],
    ],
    [
        'id' => 'wraps',
        'title' => 'Wrap & Roll',
        'wordmark' => 'wraps',
        'watermark' => 'Cheesy',
        'note' => 'Choice of white, wheat or spinach, pita. Gluten free wrap +1.50 extra',
        'items' => [
            ['name' => 'Grilled Chicken Caesar', 'desc' => 'Romaine lettuce, Parmesan cheese & homemade creamy Caesar dressing', 'price' => '9.95'],
            ['name' => 'Buffalo Chicken', 'spicy' => true, 'desc' => 'Breaded chicken tossed in buffalo sauce with lettuce, tomato & blue cheese', 'price' => '9.95'],
            ['name' => 'Gyro', 'desc' => 'Choice of thinly sliced chicken or lamb with lettuce, tomato & onion with tzatziki sauce on pita wrap', 'price' => '9.95'],
            ['name' => 'Shawarma', 'desc' => 'Thinly sliced chicken grilled to perfection, with lettuce, tomato, onion & garlic sauce', 'price' => '9.95'],
            ['name' => 'Falafel', 'veg' => true, 'desc' => 'Lettuce, tomato, tahini & hummus on pita wrap', 'price' => '8.95'],
            ['name' => 'Kebab', 'desc' => 'Chicken with lettuce, tomato & onion, garlic sauce on pita wrap', 'price' => '9.95'],
            ['name' => 'Chicken Milanese', 'desc' => 'Breaded chicken, mozzarella cheese, arugula, roasted red peppers, red onions with balsamic vinaigrette', 'price' => '9.95'],
            ['name' => 'Honey Chicken', 'desc' => 'Breaded chicken, lettuce, tomato & crispy bacon with honey mustard', 'price' => '9.95'],
        ],
    ],
    [
        'id' => 'pasta',
        'title' => 'Pastabilities',
        'wordmark' => 'pasta',
        'watermark' => 'Food Of Love',
        'items' => [
            ['name' => 'Penne Alla Vodka', 'desc' => 'Penne pasta tossed in a creamy pink sauce (try it spicy)', 'price' => '13.95'],
            ['name' => 'Pasta Bolognese', 'desc' => 'Diced onions, fresh garlic & ground beef, sautéed then cooked in our homemade marinara sauce & touch of cream', 'price' => '15.95'],
            ['name' => 'Pasta Marinara', 'desc' => 'Penne pasta with our homemade marinara sauce', 'price' => '9.95'],
            ['name' => 'Cajun Alfredo', 'spicy' => true, 'desc' => 'Roasted red peppers and bacon sautéed then tossed in a creamy alfredo sauce', 'price' => '14.95'],
            ['name' => 'Tortellini Leo', 'desc' => 'Tricolor cheese tortellini pasta, sun-dried tomatoes, fresh spinach & fresh garlic sautéed in creamy pink vodka sauce topped with pecorino cheese', 'price' => '14.95'],
        ],
    ],
    [
        'id' => 'cheesesteak',
        'title' => 'Cheesesteak',
        'wordmark' => 'cheesesteak',
        'watermark' => 'Straight Outta Bville',
        'items' => [
            ['name' => 'Philly Cheesesteak', 'slug' => 'italian-sub', 'desc' => 'Shredded steak, onions, peppers with American cheese', 'price' => '9.95'],
            ['name' => 'Jersey Cheesesteak', 'desc' => 'With brown gravy potatoes & mozzarella cheese', 'price' => '10.95'],
            ['name' => 'California Cheesesteak', 'desc' => 'With lettuce, tomato, mayonnaise & American cheese', 'price' => '10.95'],
            ['name' => 'Chicken Cheesesteak', 'desc' => 'Thinly sliced chicken breast, sautéed mushrooms, peppers, onions & American cheese', 'price' => '9.95'],
        ],
    ],
    [
        'id' => 'sandwiches',
        'title' => 'Sandwiches',
        'wordmark' => 'sandwiches',
        'items' => [
            ['name' => 'Chicken Parmesan', 'desc' => 'Try it with pink vodka sauce +1', 'price' => '10.95'],
            ['name' => 'Meatball Parmesan', 'price' => '10.95'],
            ['name' => 'Buttermilk Fried Chicken Sandwich', 'desc' => 'With lettuce, tomato & onion', 'price' => '10.95'],
            ['name' => 'Grilled Chicken', 'desc' => 'Lettuce, tomato & mayo', 'price' => '9.95'],
            ['name' => 'Pastrami Reuben', 'desc' => 'Sliced pastrami, sauerkraut, Russian dressing & Swiss cheese on rye toast', 'price' => '10.95'],
            ['name' => 'Buffalo Chicken', 'spicy' => true, 'desc' => 'Lettuce, tomato & blue cheese', 'price' => '10.95'],
            ['name' => 'Italian Hot Dog', 'desc' => 'Sliced hot dog, potatoes, peppers, onions', 'price' => '9.95'],
            ['name' => 'Hot Pastrami', 'desc' => 'Sliced pastrami, Swiss cheese & mustard on rye bread', 'price' => '10.95'],
            ['name' => 'Tuna Melt', 'desc' => 'Solid white tuna with mayo & melted American cheese, served on white toast', 'price' => '9.95'],
            ['name' => 'Turkey Club', 'desc' => 'Turkey, bacon, lettuce, tomato & mayo on white toast', 'price' => '9.95'],
        ],
    ],
    [
        'id' => 'panini',
        'title' => 'Panini',
        'wordmark' => 'panini',
        'watermark' => 'Toasty',
        'items' => [
            ['name' => 'Chipotle Chicken', 'spicy' => true, 'desc' => 'Char-grilled chicken, avocado & pepper jack cheese with homemade chipotle mayo', 'price' => '9.95'],
            ['name' => 'Chicken', 'desc' => 'Char-grilled chicken, roasted peppers & mozzarella cheese with balsamic glaze', 'price' => '9.95'],
            ['name' => 'Veggie', 'veg' => true, 'desc' => 'Grilled eggplant, roasted red peppers & mozzarella cheese with balsamic glaze', 'price' => '9.95'],
            ['name' => 'Milano', 'desc' => 'Char-grilled chicken, pesto, roasted peppers, arugula & melted mozzarella cheese', 'price' => '10.95'],
            ['name' => 'Turkey', 'desc' => 'Oven-roasted turkey, roasted peppers & mozzarella cheese with balsamic glaze', 'price' => '9.95'],
        ],
    ],
    [
        'id' => 'pizza',
        'title' => 'Stone Oven Baked',
        'wordmark' => 'pizza',
        'watermark' => "It's Pizza Time",
        'note' => 'Customize your pizza sauce: Fra Diavolo (spicy) +1 · B-ville pink vodka sauce +2 extra',
        'sizes' => ['12"', '16"'],
        'items' => [
            ['name' => 'Regular Classic Pizza', 'price_12' => '9.95', 'price_16' => '14.95'],
            ['name' => 'Margherita', 'slug' => 'margherita', 'veg' => true, 'desc' => 'Fresh mozzarella, fresh basil & pizza sauce', 'price_12' => '13.95', 'price_16' => '18.95'],
            ['name' => 'Meat Lover\'s', 'desc' => 'Pepperoni, sausage, bacon & meatballs', 'price_12' => '14.95', 'price_16' => '22.95'],
            ['name' => 'White Pie', 'desc' => 'Mozzarella & ricotta cheese', 'price_12' => '13.95', 'price_16' => '18.95'],
            ['name' => 'Chicken Parmesan', 'desc' => 'Breaded chicken cutlet, pomodoro sauce mozzarella & fresh basil', 'price_12' => '14.95', 'price_16' => '21.95'],
            ['name' => 'BBQ or Buffalo Chicken', 'price_12' => '15.95', 'price_16' => '21.95'],
            ['name' => 'Vegetarian Lover\'s', 'veg' => true, 'desc' => 'Peppers, onions, mushrooms & olives', 'price_12' => '12.95', 'price_16' => '19.95'],
            ['name' => 'Philly Cheesesteak', 'desc' => 'Sautéed beef, onions, peppers, mushrooms & mozzarella cheese topped with American cheese', 'price_12' => '15.95', 'price_16' => '23.95'],
            ['name' => 'B\'Ville Special', 'slug' => 'bville-special', 'desc' => 'Shawarma chicken, lettuce, tomato, onion & parsley with garlic sauce drizzle', 'price_12' => '14.95', 'price_16' => '20.95'],
            ['name' => 'Sesame Thai Chili', 'spicy' => true, 'desc' => 'Thai chili spread topped with sesame chicken, mozzarella and garnished with ranch dressing', 'price_12' => '14.95', 'price_16' => '22.95'],
            ['name' => 'Don Pomodoro', 'veg' => true, 'desc' => 'Mozzarella, fresh plum tomatoes, fresh basil garnished with grated pecorino cheese', 'price_12' => '13.95', 'price_16' => '17.95'],
            ['name' => 'Combination', 'desc' => 'Pepperoni, sausage, mushroom, onion & peppers', 'price_12' => '14.95', 'price_16' => '22.95'],
        ],
    ],
    [
        'id' => 'platters',
        'title' => 'Headlines',
        'wordmark' => 'platters',
        'watermark' => 'Eat All About It',
        'items' => [
            ['name' => 'Char-Grilled Shrimp Kababs', 'desc' => 'Served with house salad', 'price' => '17.95'],
            ['name' => 'Norwegian Salmon', 'desc' => 'Fresh, hand-cut, lightly seasoned & grilled salmon served with house salad', 'price' => '16.95'],
            ['name' => 'Gyro', 'desc' => 'Sliced fresh lamb served with tzatziki sauce, rice & house salad', 'price' => '14.95'],
            ['name' => 'Falafel Platter', 'veg' => true, 'desc' => 'Ground chick peas, onions, garlic, parsley, & our secret spice blend, served with tahini sauce, rice & house salad', 'price' => '12.95'],
            ['name' => 'Chicken Kabab', 'slug' => 'lamb-skewers', 'desc' => 'Char-grilled marinated chicken breast served with rice, salad and topped with sautéed onions & peppers', 'price' => '14.95'],
            ['name' => 'Chicken Gyro', 'desc' => 'Greek-style sliced chicken breast with peppers & onions, served with rice, salad & tzatziki sauce', 'price' => '14.95'],
            ['name' => 'Shawarma', 'desc' => 'Marinated & thinly sliced chicken breast with sautéed peppers & onions. Served with rice, salad & garlic sauce', 'price' => '14.95'],
            ['name' => 'Chicken Parmesan', 'desc' => 'Breaded chicken breast topped with our homemade marinara sauce & mozzarella, served over pasta', 'price' => '15.95'],
            ['name' => 'Chicken Quesadilla', 'desc' => 'Sautéed marinated chicken with onions & peppers', 'price' => '11.95'],
            ['name' => 'Sausage, Peppers & Onion Parmesan', 'price' => '12.95'],
            ['name' => 'Eggplant Parmesan', 'veg' => true, 'desc' => 'Eggplant cutlets, marinara & mozzarella cheese, topped with grated pecorino', 'price' => '12.95'],
        ],
    ],
    [
        'id' => 'kids',
        'title' => 'Kids Menu',
        'wordmark' => 'kids',
        'watermark' => 'Fun Foods',
        'note' => 'Choice of fries or broccoli on grilled cheese, tenders & hot dog. Mac & cheese and pasta not served with a side.',
        'items' => [
            ['name' => 'Grilled Cheese', 'desc' => 'Choice of fries or broccoli', 'price' => '7.95'],
            ['name' => 'Chicken Tenders', 'desc' => 'Choice of fries or broccoli', 'price' => '7.95'],
            ['name' => 'Hot Dog', 'desc' => 'Choice of fries or broccoli', 'price' => '7.95'],
            ['name' => 'Mac & Cheese', 'desc' => 'Not served with a side', 'price' => '7.95'],
            ['name' => 'Pasta with Butter or Marinara', 'desc' => 'Not served with a side', 'price' => '7.95'],
        ],
    ],
    [
        'id' => 'desserts',
        'title' => 'Sweet Endings',
        'wordmark' => 'desserts',
        'watermark' => 'Italian Favorites',
        'note' => 'All 5.95',
        'items' => [
            ['name' => 'Coppa Yogurt & Berries', 'desc' => 'Yogurt gelato swirled together with mixed berry sauce, topped with blueberries and currants', 'price' => '5.95', 'photo' => 'gelato-yogurt-berries'],
            ['name' => 'Espresso Creme Brulee', 'desc' => 'Creamy custard flavored with espresso, topped with caramelized sugar', 'price' => '5.95', 'photo' => 'gelato-creme-brulee'],
            ['name' => 'Coppa Mascarpone', 'desc' => 'A chocolate cream followed by a smooth mascarpone cream, topped with Amaretto cookie crumbs and chocolate curls', 'price' => '5.95', 'photo' => 'gelato-mascarpone'],
            ['name' => 'Limoncello Flute', 'desc' => 'Refreshing lemon gelato made with lemons from Sicily, swirled together with Limoncello sauce', 'price' => '5.95', 'photo' => 'gelato-limoncello'],
            ['name' => 'Hazelnut Chocolate Flute', 'desc' => 'Smooth hazelnut gelato swirled with rich chocolate sauce presented in a flute glass', 'price' => '5.95', 'photo' => 'gelato-hazelnut'],
            ['name' => 'Coppa Spagnola', 'desc' => 'Vanilla and Amarena cherry gelato swirled together, topped with real Amarena cherries', 'price' => '5.95', 'photo' => 'gelato-spagnola'],
            ['name' => 'Coppa Stracciatella', 'desc' => 'Chocolate chip gelato swirled together with chocolate syrup, topped with cocoa powder and hazelnuts', 'price' => '5.95', 'photo' => 'gelato-stracciatella'],
            ['name' => 'Coppa Pistachio', 'desc' => 'Custard gelato swirled with chocolate and pistachio gelato topped with praline pistachios', 'price' => '5.95', 'photo' => 'gelato-pistachio'],
            ['name' => 'Guava Mango Flute', 'desc' => 'Creamy tropical guava gelato swirled with sweet mango sauce', 'price' => '5.95', 'photo' => 'gelato-guava'],
            ['name' => 'Coppa Cafe', 'desc' => 'Fior di latte gelato with rich coffee and pure cocoa swirl', 'price' => '5.95', 'photo' => 'gelato-cafe'],
            ['name' => 'Coppa Catalana', 'desc' => 'Creamy custard topped with caramelized sugar', 'price' => '5.95', 'photo' => 'gelato-espresso'],
        ],
    ],
];
