<?php

declare(strict_types=1);

return [
    [
        'id' => 'pizza',
        'title' => 'Stone Oven Pizza',
        'watermark' => 'Baked',
        'note' => 'Customize your pizza sauce: Fra Diavolo (spicy) +1 · B-ville pink vodka sauce +2',
        'sizes' => ['12"', '16"'],
        'items' => [
            ['name' => 'Regular Classic Pizza', 'price_12' => '9.95', 'price_16' => '14.95'],
            ['name' => 'Margherita', 'slug' => 'margherita', 'veg' => true, 'desc' => 'Fresh mozzarella, fresh basil & pizza sauce', 'price_12' => '13.95', 'price_16' => '18.95'],
            ['name' => 'Meat Lover\'s', 'desc' => 'Pepperoni, sausage, bacon & meatballs', 'price_12' => '14.95', 'price_16' => '22.95'],
            ['name' => 'White Pie', 'desc' => 'Mozzarella & ricotta cheese', 'price_12' => '13.95', 'price_16' => '18.95'],
            ['name' => 'Chicken Parmesan', 'desc' => 'Breaded chicken cutlet, pomodoro sauce, mozzarella & fresh basil', 'price_12' => '14.95', 'price_16' => '21.95'],
            ['name' => 'BBQ or Buffalo Chicken', 'price_12' => '15.95', 'price_16' => '21.95'],
            ['name' => 'Vegetarian Lover\'s', 'veg' => true, 'desc' => 'Peppers, onions, mushrooms & olives', 'price_12' => '12.95', 'price_16' => '19.95'],
            ['name' => 'Philly Cheesesteak', 'desc' => 'Sautéed beef, onions, peppers, mushrooms & mozzarella topped with American cheese', 'price_12' => '15.95', 'price_16' => '23.95'],
            ['name' => 'B\'Ville Special', 'slug' => 'bville-special', 'desc' => 'Shawarma chicken, lettuce, tomato, onion & parsley with garlic sauce drizzle', 'price_12' => '14.95', 'price_16' => '20.95'],
            ['name' => 'Sesame Thai Chili', 'spicy' => true, 'desc' => 'Thai chili spread topped with sesame chicken, mozzarella, ranch garnish', 'price_12' => '14.95', 'price_16' => '22.95'],
            ['name' => 'Don Pomodoro', 'veg' => true, 'desc' => 'Mozzarella, fresh plum tomatoes, fresh basil, grated pecorino', 'price_12' => '13.95', 'price_16' => '17.95'],
            ['name' => 'Combination', 'desc' => 'Pepperoni, sausage, mushroom, onion & peppers', 'price_12' => '14.95', 'price_16' => '22.95'],
        ],
    ],
    [
        'id' => 'platters',
        'title' => 'Platters',
        'watermark' => 'Headliners',
        'items' => [
            ['name' => 'Char-Grilled Shrimp Kababs', 'desc' => 'Served with house salad', 'price' => '17.95'],
            ['name' => 'Norwegian Salmon', 'desc' => 'Fresh, hand-cut, lightly seasoned & grilled, served with house salad', 'price' => '16.95'],
            ['name' => 'Falafel Platter', 'veg' => true, 'desc' => 'Ground chick peas, onions, garlic, parsley & secret spice blend, tahini, rice & house salad', 'price' => '12.95'],
            ['name' => 'Gyro', 'desc' => 'Sliced fresh lamb with tzatziki, rice & house salad', 'price' => '14.95'],
            ['name' => 'Chicken Kabab', 'slug' => 'lamb-skewers', 'desc' => 'Char-grilled marinated chicken breast, rice, salad, sautéed onions & peppers', 'price' => '14.95'],
            ['name' => 'Chicken Gyro', 'desc' => 'Greek-style sliced chicken with peppers & onions, rice, salad & tzatziki', 'price' => '14.95'],
            ['name' => 'Shawarma', 'desc' => 'Marinated thinly sliced chicken with peppers & onions, rice, salad & garlic sauce', 'price' => '14.95'],
            ['name' => 'Chicken Parmesan', 'desc' => 'Breaded chicken breast, homemade marinara & mozzarella, served over pasta', 'price' => '15.95'],
            ['name' => 'Chicken Quesadilla', 'desc' => 'Sautéed marinated chicken with onions & peppers', 'price' => '11.95'],
            ['name' => 'Sausage, Peppers & Onion Parmesan', 'price' => '12.95'],
            ['name' => 'Eggplant Parmesan', 'veg' => true, 'desc' => 'Eggplant cutlets, marinara & mozzarella, grated pecorino', 'price' => '12.95'],
        ],
    ],
    [
        'id' => 'garden',
        'title' => 'From The Garden',
        'watermark' => 'Fresh Salad',
        'note' => 'Add-ons: Chicken 4 · Grilled Salmon 7 · Shawarma 6 · Tuna Salad 4 · Steak 8 · Gyro (Lamb) 5 · Chicken Kabab 7 · Buffalo Chicken 4 · Cajun Salmon 8 · Cajun Chicken 5 · Shrimp 6',
        'items' => [
            ['name' => 'House', 'desc' => 'Romaine, tomatoes, cucumbers, carrots & red onions with oil & vinegar', 'price' => '7.95'],
            ['name' => 'Greek', 'desc' => 'Romaine, tomatoes, cucumbers, olives, red onions & feta with greek vinaigrette', 'price' => '9.95'],
            ['name' => 'Caesar', 'desc' => 'Romaine, freshly made Caesar dressing, parmesan & croutons', 'price' => '7.95'],
            ['name' => 'Baby Spinach', 'desc' => 'Spinach, strawberries, walnuts & goat cheese with balsamic vinaigrette', 'price' => '9.95'],
            ['name' => 'Arugula', 'desc' => 'Roasted red peppers, red onions, Parmesan, balsamic glaze', 'price' => '9.95'],
            ['name' => 'Cobb', 'desc' => 'Mixed greens, tomatoes, cucumbers, boiled egg, blue cheese, bacon & avocado with balsamic vinaigrette', 'price' => '9.95'],
            ['name' => 'Mixed Greens', 'desc' => 'Tomato, onion, cucumber, carrots & fresh mozzarella with raspberry vinaigrette', 'price' => '9.95'],
        ],
    ],
    [
        'id' => 'starters',
        'title' => 'Let\'s Get It Started',
        'watermark' => 'Sides',
        'items' => [
            ['name' => 'Homemade Wings', 'desc' => 'Bone-in or boneless. Carrots, celery. Buffalo, teriyaki, BBQ or sweet chili', 'price' => '8.95 / 14.95', 'note' => '(6) / (12)'],
            ['name' => 'Mozzarella Sticks', 'desc' => 'Golden-fried, served with marinara', 'price' => '7.95'],
            ['name' => 'Fried Calamari', 'desc' => 'Choice of spicy or sweet marinara', 'price' => '10.95'],
            ['name' => 'Mac & Cheese Bites', 'desc' => 'Golden-fried, served with marinara', 'price' => '7.95'],
            ['name' => 'Hummus', 'veg' => true, 'desc' => 'Homemade chickpeas, lemon & tahini (pita or veggie)', 'price' => '7.95'],
            ['name' => 'Falafel Bites', 'veg' => true, 'desc' => 'Chickpeas, onion, garlic, parsley & secret spices', 'price' => '7.95'],
            ['name' => 'Teriyaki Dumplings', 'desc' => 'Fried chicken dumplings with teriyaki sauce', 'price' => '7.95'],
            ['name' => 'Burger Sliders', 'desc' => '3 mini Angus burgers with sautéed onions & cheddar', 'price' => '10.95'],
            ['name' => 'Buffalo Chicken Mac & Cheese', 'price' => '9.95'],
            ['name' => 'Chicken Nuggets & Fries', 'desc' => '6 nuggets with sauce', 'price' => '7.95'],
            ['name' => 'Chicken Tenders', 'desc' => '5 tenders with fries & sauce', 'price' => '7.95'],
            ['name' => 'Rice', 'price' => '3.95'],
            ['name' => 'Sweet Potato Fries', 'price' => '3.95'],
            ['name' => 'French Fries', 'price' => '3.95'],
            ['name' => 'Disco Fries', 'price' => '6.95'],
            ['name' => 'Onion Rings', 'price' => '5.95'],
            ['name' => 'Sautéed Veggie', 'price' => '4.95'],
        ],
    ],
    [
        'id' => 'wraps',
        'title' => 'Wraps',
        'watermark' => 'Cheesy',
        'items' => [
            ['name' => 'Grilled Chicken Caesar', 'desc' => 'Romaine, Parmesan & homemade creamy Caesar', 'price' => '9.95'],
            ['name' => 'Buffalo Chicken', 'spicy' => true, 'desc' => 'Breaded chicken tossed in buffalo sauce with lettuce, tomato & blue cheese', 'price' => '9.95'],
            ['name' => 'Gyro Wrap', 'desc' => 'Chicken or lamb with lettuce, tomato, onion & tzatziki on pita', 'price' => '9.95'],
            ['name' => 'Shawarma Wrap', 'desc' => 'Thinly sliced chicken, lettuce, tomato, onion & garlic sauce', 'price' => '9.95'],
            ['name' => 'Falafel Wrap', 'veg' => true, 'desc' => 'Lettuce, tomato, tahini & hummus on pita', 'price' => '8.95'],
            ['name' => 'Kebab Wrap', 'desc' => 'Chicken with lettuce, tomato, onion & garlic sauce on pita', 'price' => '9.95'],
            ['name' => 'Chicken Milanese', 'desc' => 'Breaded chicken, mozzarella, arugula, roasted red peppers, red onions, balsamic vinaigrette', 'price' => '9.95'],
            ['name' => 'Honey Chicken', 'desc' => 'Breaded chicken, lettuce, tomato & crispy bacon with honey mustard', 'price' => '9.95'],
        ],
    ],
    [
        'id' => 'pasta',
        'title' => 'Pastabilities',
        'watermark' => 'Cheesy',
        'items' => [
            ['name' => 'Penne Alla Vodka', 'desc' => 'Penne tossed in a creamy pink sauce — try it spicy', 'price' => '13.95'],
            ['name' => 'Pasta Bolognese', 'desc' => 'Onions, garlic & ground beef in homemade marinara with a touch of cream', 'price' => '15.95'],
            ['name' => 'Pasta Marinara', 'desc' => 'Penne with homemade marinara', 'price' => '9.95'],
            ['name' => 'Cajun Alfredo', 'spicy' => true, 'desc' => 'Roasted red peppers and bacon tossed in creamy alfredo', 'price' => '14.95'],
            ['name' => 'Tortellini Leo', 'desc' => 'Tricolor cheese tortellini, sun-dried tomatoes, fresh spinach & garlic', 'price' => '14.95'],
        ],
    ],
    [
        'id' => 'sandwiches',
        'title' => 'Sandwiches',
        'watermark' => 'Straight Outta Philly',
        'items' => [
            ['name' => 'Philly Cheesesteak', 'slug' => 'italian-sub', 'desc' => 'Shredded steak, onions, peppers with American cheese', 'price' => '9.95'],
            ['name' => 'Jersey Cheesesteak', 'desc' => 'Brown gravy, potatoes & mozzarella', 'price' => '10.95'],
            ['name' => 'California Cheesesteak', 'desc' => 'Lettuce, tomato, mayonnaise & American cheese', 'price' => '10.95'],
            ['name' => 'Chicken Parmesan Sandwich', 'desc' => 'Try it with pink vodka sauce +1', 'price' => '10.95'],
            ['name' => 'Meatball Parmesan', 'price' => '10.95'],
            ['name' => 'Buttermilk Fried Chicken Sandwich', 'desc' => 'Lettuce, tomato & onion', 'price' => '10.95'],
            ['name' => 'Grilled Chicken Sandwich', 'desc' => 'Lettuce, tomato & mayo', 'price' => '9.95'],
            ['name' => 'Pastrami Reuben', 'desc' => 'Pastrami, sauerkraut, Russian dressing & Swiss on rye toast', 'price' => '10.95'],
            ['name' => 'Buffalo Chicken Sandwich', 'spicy' => true, 'desc' => 'Lettuce, tomato & blue cheese', 'price' => '10.95'],
            ['name' => 'Italian Hot Dog', 'desc' => 'Sliced hot dog, potatoes, peppers, onions', 'price' => '9.95'],
            ['name' => 'Hot Pastrami', 'desc' => 'Pastrami, Swiss & mustard on rye', 'price' => '10.95'],
            ['name' => 'Tuna Melt', 'desc' => 'Solid white tuna with mayo & melted American on white toast', 'price' => '9.95'],
            ['name' => 'Turkey Club', 'desc' => 'Turkey, bacon, lettuce, tomato & mayo on white toast', 'price' => '9.95'],
        ],
    ],
    [
        'id' => 'panini',
        'title' => 'Panini',
        'watermark' => 'Toasty',
        'items' => [
            ['name' => 'Chipotle Chicken', 'spicy' => true, 'desc' => 'Char-grilled chicken, avocado & pepper jack with homemade chipotle mayo', 'price' => '9.95'],
            ['name' => 'Chicken Panini', 'desc' => 'Char-grilled chicken, roasted peppers & mozzarella with balsamic glaze', 'price' => '9.95'],
            ['name' => 'Veggie Panini', 'veg' => true, 'desc' => 'Grilled eggplant, roasted red peppers & mozzarella with balsamic glaze', 'price' => '9.95'],
            ['name' => 'Milano', 'desc' => 'Pressed Italian-style panini', 'price' => '10.95'],
        ],
    ],
    [
        'id' => 'burgers',
        'title' => 'Burgers',
        'watermark' => 'Beefy',
        'note' => 'Angus · Beefy — So Sweet, So Tasty, So Juicy',
        'items' => [
            ['name' => 'Classic', 'desc' => 'Lettuce, tomato & onion', 'price' => '9.95'],
            ['name' => 'Cheese Deluxe', 'desc' => 'Lettuce, tomato, onion & American cheese', 'price' => '10.95'],
            ['name' => 'The Fry', 'desc' => 'Breaded chicken cutlet, coleslaw & pickles with fry sauce', 'price' => '10.95'],
            ['name' => 'Grill Chicken Burger', 'desc' => 'American cheese, lettuce, tomato, onion, pickle', 'price' => '11.95'],
            ['name' => 'Boom Boom', 'desc' => 'Naked (no bun) lettuce, tomato, avocado, bacon & boom-boom sauce', 'price' => '11.95'],
            ['name' => 'Chetzel', 'slug' => 'prime-rib-burger', 'desc' => 'Bacon, melted cheddar & jack on a toasted pretzel bun', 'price' => '12.95'],
            ['name' => 'Shroom', 'desc' => 'Sautéed mushrooms & onions with Swiss', 'price' => '11.95'],
            ['name' => 'Falafel Burger', 'veg' => true, 'desc' => 'Lettuce, tomato & pickle with tahini', 'price' => '9.95'],
        ],
    ],
    [
        'id' => 'shakes',
        'title' => 'Shakes',
        'watermark' => 'Sweet',
        'items' => [
            ['name' => 'Milkshake', 'desc' => 'NutterButter, Cookies & Cream, Chocolate, Vanilla or Strawberry', 'price' => '4.95'],
        ],
    ],
    [
        'id' => 'kids',
        'title' => 'Kids Menu',
        'watermark' => 'Little Ones',
        'note' => 'All 7.95 — grilled cheese, tenders & hot dog with fries or broccoli',
        'items' => [
            ['name' => 'Grilled Cheese', 'desc' => 'Choice of fries or broccoli', 'price' => '7.95'],
            ['name' => 'Chicken Tenders', 'desc' => 'Choice of fries or broccoli', 'price' => '7.95'],
            ['name' => 'Hot Dog', 'desc' => 'Choice of fries or broccoli', 'price' => '7.95'],
            ['name' => 'Mac & Cheese', 'desc' => 'Not served with a side', 'price' => '7.95'],
            ['name' => 'Pasta with Butter or Marinara', 'desc' => 'Not served with a side', 'price' => '7.95'],
        ],
    ],
];
