<?php

declare(strict_types=1);

return [
    [
        'id' => 'bville-origin',
        'tag' => 'Origin',
        'year' => '2020',
        'featured' => true,
        'title' => 'The Grill Becomes Bville',
        'subtitle' => 'Same kitchen. New flame.',
        'excerpt' => 'When The Grill reopened as Bville Pizza & Grill, the promise was simple: keep every recipe neighbors trusted, and add stone-oven pizza worth the drive.',
        'quote' => 'We didn\'t change the heart of the place — we gave it a louder welcome.',
        'image' => 'assets/photos/listing/falafel-salad.jpg',
        'related_category' => 'pizza',
        'related_item' => 'bville-special',
        'read_time' => '3 min',
        'body' => [
            'For years, Bernardsville knew this address as The Grill — chicken wings on game night, paninis at lunch, kabobs that traveled well on the ride home.',
            'The rename to Bville Pizza & Grill wasn\'t a reset. It was an invitation: the Mediterranean and American plates you already loved, plus creative stone-oven pies from a oven that never cools down.',
            'Regulars still ask for the same favorites. First-timers come for the pizza and stay for everything else. That is the story we tell every night at 159 Morristown Rd.',
        ],
    ],
    [
        'id' => 'stone-oven',
        'tag' => 'Tradition',
        'year' => 'Stone',
        'title' => 'Fire in the Stone Oven',
        'subtitle' => 'Crust with memory',
        'excerpt' => 'Our stone oven holds heat like a hearth — blistered edges, soft center, toppings that stay bright.',
        'quote' => 'You hear the crackle before you taste the crust.',
        'image' => 'assets/photos/listing/pizza.jpg',
        'related_category' => 'pizza',
        'related_item' => 'margherita',
        'read_time' => '2 min',
        'body' => [
            'Stone heat does not rush. It pushes moisture out of the dough slowly, so every pie gets a leopard-spotted rim and a center that folds without breaking.',
            'The Margherita is our benchmark — basil added after the bake so it stays green. The Bville Special loads up for Friday nights. The Mediterranean pie is our love letter to the flavors that built this menu long before pizza joined it.',
        ],
    ],
    [
        'id' => 'morristown-road',
        'tag' => 'Neighborhood',
        'year' => '07924',
        'title' => 'Morristown Road Regulars',
        'subtitle' => 'Bernardsville at the counter',
        'excerpt' => 'Route 202 traffic, Little League pickup, late lunch from the train — this road feeds the room.',
        'quote' => 'Everyone has a usual. We learn yours by the second visit.',
        'image' => 'assets/photos/listing/interior.jpg',
        'related_category' => 'sandwiches',
        'related_item' => 'italian-sub',
        'read_time' => '2 min',
        'body' => [
            '159 Morristown Rd sits in the middle of errands and celebrations. Some orders are eaten in the car; some turn into a booth and a second round of fries.',
            'The Italian Sub and Philly Cheesesteak are road-trip sandwiches — built to survive the drive to Far Hills or back toward Basking Ridge. We press paninis for desk lunches and stack wraps for the pool bag.',
        ],
    ],
    [
        'id' => 'mediterranean-grill',
        'tag' => 'Heritage',
        'year' => 'Grill',
        'title' => 'Two Menus, One Pass',
        'subtitle' => 'Mediterranean meets American',
        'excerpt' => 'Kabobs and burgers share the same grill line — that is the Bville balance.',
        'quote' => 'Order lamb skewers and a friend orders wings. Both leave happy.',
        'image' => 'assets/photos/listing/chicken-platter.jpg',
        'related_category' => 'handhelds',
        'related_item' => 'lamb-skewers',
        'read_time' => '2 min',
        'body' => [
            'Before the pizza oven, this kitchen earned its stars on marinated chicken, lamb skewers, and falafel that crackle when you bite.',
            'We never treated that side of the menu as a side. It is half the identity — bright herbs, lemon, smoke from the same fire that chars a burger bun.',
        ],
    ],
    [
        'id' => 'angus-prime',
        'tag' => 'Burgers',
        'year' => 'Angus',
        'title' => 'So Sweet, So Tasty, So Juicy',
        'subtitle' => 'Angus · Prime Rib',
        'excerpt' => 'Three words on the board, one standard in the kitchen: burgers that do not dry out.',
        'quote' => 'Prime Rib Burger night is when the whole room smells like caramelized onion.',
        'image' => 'assets/photos/listing/chicken-pesto-sub.jpg',
        'related_category' => 'burgers',
        'related_item' => 'prime-rib-burger',
        'read_time' => '2 min',
        'body' => [
            'The burgundy board out front is not decoration — it is a dare. Angus beef, aged cheddar, bacon that stays crisp, brioche that holds the juice.',
            'Classic for the kids. Prime Rib for the regular who knows. Bville Bacon for everyone who wants the house sauce on everything.',
        ],
    ],
    [
        'id' => 'cafe-robust',
        'tag' => 'Coffee',
        'year' => 'CR',
        'title' => 'Cafe Robust at Bville',
        'subtitle' => 'Bold coffee · Fresh roasts',
        'excerpt' => 'Morning espresso, afternoon cold brew — Cafe Robust lives inside Bville the way a good bar always should.',
        'quote' => 'The bean emblem on the cup is a promise: dark roast, no shortcuts.',
        'image' => 'assets/photos/coffee.jpg',
        'related_category' => 'cafe',
        'related_item' => 'robust-house-blend',
        'read_time' => '2 min',
        'body' => [
            'Cafe Robust is not a separate shop — it is the smell when you walk in before noon. House blend for the regulars, cappuccino for the meeting, cold brew for the ride down 202.',
            'Brown and gold on the logo, warmth in the cup. Ask the barista for the seasonal special; they rotate it when the weather turns.',
        ],
    ],
    [
        'id' => 'philhower-brand',
        'tag' => 'Design',
        'year' => 'Studio',
        'title' => 'Branding with Philhower',
        'subtitle' => 'Warped Minds Design',
        'excerpt' => 'The marks on the menu, the Cafe Robust cup, the energy on the page — David Philhower shaped how Bville looks when you are hungry.',
        'quote' => 'Good branding should feel like the place already smells good.',
        'image' => 'assets/photos/listing/menu-cover.jpg',
        'related_category' => null,
        'related_item' => null,
        'read_time' => '1 min',
        'body' => [
            'Every neighborhood spot needs a face. Philhower gave Bville and Cafe Robust theirs — bold color, readable type, logos that work on a door sticker and a phone screen.',
            'When the food is honest, the design should be too. That is why the credits stay in the footer: the story of the meal and the story of the mark share the same table.',
        ],
    ],
];
